version: '3.8'

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    environment:
      REACT_APP_API_SERVER: "localhost"
    ports:
      - 3000:3000
    volumes:
      - ./web/node_modules:/app/node_modules
      - ./web/src:/app/src
    depends_on:
      api:
        condition: service_started
    networks:
      - dev

  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      MYSQL_DATABASE: 'chat-app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
      DB_HOST: "mysql"
      JWT_SECRET: "my-super-secret"
      COOKIE_SECRET: "my-super-secret"
      CLIENT_ORIGIN: "http://localhost:3000"
    ports:
      - 8000:8000
    volumes:
      - ./server/node_modules:/app/node_modules
      - ./server/src:/app/src
    depends_on:
      mysql:
        condition: service_started
    networks:
      - dev

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'chat-app'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
    networks:
      - dev

volumes:
  my-db:

networks:
  dev:
    driver: bridge